### variables
@url = http://localhost:3000

### get todos
GET {{url}}/api/todos HTTP/1.1
### get todo by id
GET {{url}}/api/todos/1 HTTP/1.1
### create todo
POST {{url}}/api/todos HTTP/1.1
content-type: application/json

{
    "text": "Go to the market"
}

### update todo
PUT {{url}}/api/todos/16 HTTP/1.1
content-type: application/json

{
    "text": "Go to bedas"
}

### delete todo
DELETE {{url}}/api/todos/1 HTTP/1.1